### ISSUE TITLE
Library of samples "ChezRay" not included in binary

### ISSUE THREAD

**Issue by csrabak** [AmziLS/distribution#11]
The module pointed to by the ```file:///C:/Amzi/apls/samples/chezray/doc.html in the doc page```  ```file:///<installed drive>:/<Installed Dir>/apls/docs/pro/ref_math.htm#MathematicalGames ``` is not included in the binary installation file [amzi_apls_win64_10-0-07.zip](https://github.com/AmziLS/distribution/blob/master/amzi_apls_win64_10-0-07.zip).

**Comment by DennisMerritt** [comment]
Hi Cesar,

You can get it from GitHub.

https://github.com/AmziLS/apls/tree/master/samples/chezray <https://github.com/AmziLS/apls/tree/master/samples/chezray>

—Dennis

**Comment by csrabak** [comment]
Thanks!

Should we propose a PL so the docs point to the correct way of getting them?

**Comment by DennisMerritt** [comment]
Sorry for the delay…

That would be fine.  I believe we’ve got two people who can do what needs to be done, but if not I could do it.

—Dennis

**Comment by csrabak** [comment]
OK.
So considering it would redundant to put a PL to a subject already cleared I think we can close this without prejudice.

thanks
